### ISSUE TITLE
User s rolou shop-manager nemoze exportovat objednavky

### ISSUE THREAD

**Issue by jasomdotnet** [fhbgroup/woocommerce-fhb-api#2]
Nazdarky,
user s rolou shop-manager nemoze exportovat objednavky. Vidi tlaciko exportovat, moze ho aj stlacit ale koliesko sa nikdy nedotoci (export neprebehne). Exportovat objednavky moze iba admin. 

Spravte tak, aby export mohol robit aj shop-admin. Vdaka.

**Comment by jasomdotnet** [comment]
v akom je toto stave? som stiahol najnovsiu verziu (5 dni staru) a tak z rychlika ju otestoval a stale to nefunguje.

**Comment by Kollarovic** [comment]
Dohodnite sa s majiteľmi FHB. Ak to schvália, tak sa to tam dorobí.

Kontakt https://www.fulfillment.sk/kontakt/
